# Generated by Django 5.1.6 on 2025-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
